#!/bin/bash
# Request nodes
#PBS -l nodes=2:ppn=2
#PBS -l walltime=01:00:00
# Submit to test queue
#PBS -q teaching
export OMP_NUM_THREADS=16

# Define the working directory
export MYDIR="/panfs/panasas01/phys/tk15999/MAP/bin"
# cd into working directory
cd $MYDIR

#------------------------------------------
# Determine which nodes the job has
# been allocated to and create a 
# machinefile for mpirun
#---------------------------------------------
# Do not change anything below this line
#----------------------------------------------
# Get the job number
export JOBNO="`echo $PBS_JOBID | sed s/.master.cm.cluster//`"
# Generate mpirun machinefile ---------------
export CONF="$MYDIR/machines.$JOBNO"

# Create the MPI node file 
# with each node included once
# Hence the uniq command

for  i in  `cat $PBS_NODEFILE | uniq`;
do echo $i >> $CONF
done
# Get number of processors ------------------
# Want 1 MPI thread per node, so count NODES in
# $CONF
export numnodes=`cat $CONF|wc -l`
#Execute the code --------------------------
time mpirun -machinefile $CONF -np $numnodes ./executable
